[project]
name = "papernestextension"
version = "1.1.0"
description = "Extension pour PaperNest"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Développeur PaperNest", email = "developer@papernest.io" }
]
dependencies = [
    "flet==0.85.3",
]

[dependency-groups]
dev = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]"
]

[project.urls]
Homepage = "https://github.com/Drenae/PaperNestExtension"
Documentation = "https://github.com/Drenae/PaperNestExtension"
Repository = "https://github.com/Drenae/PaperNestExtension"
Issues = "https://github.com/Drenae/PaperNestExtension/issues"

[tool.setuptools.package-data]
"flutter.papernestextension" = ["**/*"]

[tool.setuptools]
license-files = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
